package com.lootbeams.compat;

import com.lootbeams.LootBeams;
import me.shedaniel.clothconfig2.api.ConfigBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.TextComponent;

import java.util.ArrayList;

public class LootBeamsConfigScreen {
    public static Screen getConfigScreen(Screen parent){
        ConfigBuilder builder = ConfigBuilder.create();
        if (parent != null) builder.setParentScreen(parent);
        builder.setTitle(new TextComponent("Loot Beams"));
        var main = builder.getOrCreateCategory(new TextComponent("Main"));
        main.addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Render Name Color"), LootBeams.config.renderNameColor)
                        .setDefaultValue(true)
                        .setSaveConsumer(flag -> LootBeams.config.renderNameColor = flag)
                        .setTooltip(new TextComponent("If beams should be colored the same as the Items name (excludes name colors from rarity). \nThis has priority over render_rarity_color."))
                .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Render Rarity Color"), LootBeams.config.renderRarityColor)
                        .setDefaultValue(true)
                        .setSaveConsumer(flag -> LootBeams.config.renderRarityColor = flag)
                        .setTooltip(new TextComponent("If beams should be colored the same as the Items rarity."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Beam Radius"), LootBeams.config.beamRadius)
                        .setDefaultValue(1)
                        .setMin(0)
                        .setMax(5)
                        .setSaveConsumer(value -> LootBeams.config.beamRadius = value)
                        .setTooltip(new TextComponent("The radius of the Loot Beam."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Beam Height"), LootBeams.config.beamHeight)
                        .setDefaultValue(1)
                        .setMin(0)
                        .setMax(10)
                        .setSaveConsumer(value -> LootBeams.config.beamHeight = value)
                        .setTooltip(new TextComponent("The height of the Loot Beam."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Beam Y Offset"), LootBeams.config.beamYOffset)
                        .setDefaultValue(0)
                        .setMin(-30)
                        .setMax(30)
                        .setSaveConsumer(value -> LootBeams.config.beamYOffset = value)
                        .setTooltip(new TextComponent("The Y-offset of the loot beam."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Beam Alpha"), LootBeams.config.beamAlpha)
                        .setDefaultValue(0.85f)
                        .setMin(0)
                        .setMax(1)
                        .setSaveConsumer(value -> LootBeams.config.beamAlpha = value)
                        .setTooltip(new TextComponent("Transparency of the Loot Beam."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Render Distance"), LootBeams.config.renderDistance)
                        .setDefaultValue(24)
                        .setMin(0)
                        .setMax(24)
                        .setSaveConsumer(value -> LootBeams.config.renderDistance = value)
                        .setTooltip(new TextComponent("How close the player has to be to see the beam.\n (note: ItemEntities stop rendering at 24 blocks, so that is the limit for beams)"))
                        .build())
                .addEntry(builder.entryBuilder().startStrList(new TextComponent("Color Overrides"), LootBeams.config.colorOverrides)
                        .setDefaultValue(new ArrayList<>())
                        .setSaveConsumer(value -> LootBeams.config.colorOverrides = value)
                        .setTooltip(new TextComponent("Overrides an item's beam color with hex color.\n Must follow the specific format: (registryname=hexcolor) Or (#tagname=hexcolor).\n Example: \"minecraft:stone=0xFFFFFF\". This also accepts modids."))
                        .build());
        var items = builder.getOrCreateCategory(new TextComponent("Items"));
        items.addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("All Items"), LootBeams.config.allItems)
                        .setDefaultValue(true)
                        .setSaveConsumer(flag -> LootBeams.config.allItems = flag)
                        .setTooltip(new TextComponent("If all Items Loot Beams should be rendered.\n Has priority over only_equipment and only_rare."))
                .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Only Rare"), LootBeams.config.onlyRare)
                        .setDefaultValue(false)
                        .setSaveConsumer(flag -> LootBeams.config.onlyRare = flag)
                        .setTooltip(new TextComponent("If Loot Beams should only be rendered on items with rarity."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Only Equipment"), LootBeams.config.onlyEquipment)
                        .setDefaultValue(false)
                        .setSaveConsumer(flag -> LootBeams.config.onlyEquipment = flag)
                        .setTooltip(new TextComponent("If Loot Beams should only be rendered on equipment.\n (Equipment includes: Swords, Tools, Armor, Shields, Bows, Crossbows, Tridents, Arrows, and Fishing Rods)"))
                        .build())
                .addEntry(builder.entryBuilder().startStrList(new TextComponent("Whitelist"), LootBeams.config.whitelist)
                        .setDefaultValue(new ArrayList<>())
                        .setSaveConsumer(value -> LootBeams.config.whitelist = value)
                        .setTooltip(new TextComponent("Registry names of items that Loot Beams should render on.\n Example: \"minecraft:stone\", \"minecraft:iron_ingot\", \nYou can also specify modids for a whole mod's items."))
                        .build())
                .addEntry(builder.entryBuilder().startStrList(new TextComponent("Blacklist"), LootBeams.config.blacklist)
                        .setDefaultValue(new ArrayList<>())
                        .setSaveConsumer(value -> LootBeams.config.blacklist = value)
                        .setTooltip(new TextComponent("Registry names of items that Loot Beams should NOT render on. This has priority over everything.\n You can also specify modids for a whole mod's items."))
                        .build());
        var nametags = builder.getOrCreateCategory(new TextComponent("Nametags"));
        nametags.addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Borders"), LootBeams.config.borders)
                        .setDefaultValue(true)
                        .setSaveConsumer(value -> LootBeams.config.borders = value)
                        .setTooltip(new TextComponent("Render nametags as bordered. Set to false for flat nametag with background."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Render Nametags"), LootBeams.config.renderNametags)
                        .setDefaultValue(true)
                        .setSaveConsumer(value -> LootBeams.config.renderNametags = value)
                        .setTooltip(new TextComponent("If Item nametags should be rendered."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Render Nametags On Look"), LootBeams.config.renderNametagsOnlook)
                        .setDefaultValue(true)
                        .setSaveConsumer(value -> LootBeams.config.renderNametagsOnlook = value)
                        .setTooltip(new TextComponent("If Item nametags should be rendered when looking at items."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("Render Stack Count"), LootBeams.config.renderStackcount)
                        .setDefaultValue(true)
                        .setSaveConsumer(value -> LootBeams.config.renderStackcount = value)
                        .setTooltip(new TextComponent("If the count of item's should also be shown in the nametag."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Nametag Look Sensitivity"), LootBeams.config.nametagLookSensitivity)
                        .setDefaultValue(0.018f)
                        .setMin(0)
                        .setMax(5)
                        .setSaveConsumer(value -> LootBeams.config.nametagLookSensitivity = value)
                        .setTooltip(new TextComponent("How close the player has to look at the item to render the nametag."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Nametag Text Alpha"), LootBeams.config.nametagTextAlpha)
                        .setDefaultValue(1)
                        .setMin(0)
                        .setMax(1)
                        .setSaveConsumer(value -> LootBeams.config.nametagTextAlpha = value)
                        .setTooltip(new TextComponent("Transparency of the nametag text."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Nametag Background Alpha"), LootBeams.config.nametagBackgroundAlpha)
                        .setDefaultValue(0.5f)
                        .setMin(0)
                        .setMax(1)
                        .setSaveConsumer(value -> LootBeams.config.nametagBackgroundAlpha = value)
                        .setTooltip(new TextComponent("Transparency of the nametag background/border."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Nametag Scale"), LootBeams.config.nametagScale)
                        .setDefaultValue(1)
                        .setMin(-10)
                        .setMax(10)
                        .setSaveConsumer(value -> LootBeams.config.nametagScale = value)
                        .setTooltip(new TextComponent("Scale of the nametag."))
                        .build())
                .addEntry(builder.entryBuilder().startFloatField(new TextComponent("Nametag Y Offset"), LootBeams.config.nametagYOffset)
                        .setDefaultValue(0.75f)
                        .setMin(-30)
                        .setMax(30)
                        .setSaveConsumer(value -> LootBeams.config.nametagYOffset = value)
                        .setTooltip(new TextComponent("The Y-offset of the nametag."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("DMCLoot Compat Rarity"), LootBeams.config.dmclootCompatRarity)
                        .setDefaultValue(true)
                        .setSaveConsumer(value -> LootBeams.config.dmclootCompatRarity = value)
                        .setTooltip(new TextComponent("If a smaller tag should be rendered under with DMCLoot rarities."))
                        .build())
                .addEntry(builder.entryBuilder().startStrList(new TextComponent("Custom Rarities"), LootBeams.config.customRarities)
                        .setDefaultValue(new ArrayList<>())
                        .setSaveConsumer(value -> LootBeams.config.customRarities = value)
                        .setTooltip(new TextComponent("Define what the smaller tag should render on. \nExample: \"Exotic\", \"Ancient\". \nThe string supplied has to be the tooltip line below the name. \nThis is really only used for modpacks."))
                        .build())
                .addEntry(builder.entryBuilder().startBooleanToggle(new TextComponent("White Rarities"), LootBeams.config.whiteRarities)
                        .setDefaultValue(false)
                        .setSaveConsumer(value -> LootBeams.config.whiteRarities = value)
                        .setTooltip(new TextComponent("If rarities should ignore color and render as white \n(This is really only used for modpacks)"))
                        .build());
        builder.setSavingRunnable(() -> LootBeams.config.save());
        return builder.build();
    }
}
